run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gofmt
    - goimports
    - revive
  disable:
    - depguard

issues:
  exclude-use-default: false
  exclude-dirs:
    - vendor

severity:
  default-severity: error
